### ISSUE TITLE
Missing Features Aggregate

### ISSUE THREAD

**Issue by yordis** [integrations/terraform-provider-github#379]
Based on the current GitHub UI, this is the list of missing features and their statuses

- [x] As Template Repo #357
- [x] Automatically delete head branches #399
- [x] Issues Templates  #286
- [x] Sponsorships  #286
- [x] Security alerts #444 
- [x] GitHub Pages #141 
- [x] Branches Require linear history #305 #238
- [ ] [Actions permissions](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#enabling-workflows-for-private-repository-forks)
- [x] Secrets #362
- [ ] Notifications

**Comment by benj-fletch** [comment]
Hi @yordis, thanks for raising an issue and compiling this list!
I understand your want to replicate the GitHub UI with Terraform but we can only interact with GitHub via the [API](https://developer.github.com/v3/). Outside of those points which already have a ticket, are you able to confirm your needs are possible to be fulfilled via the API?

**Comment by yordis** [comment]
@benj-fletch this is why I have created the aggregate 😄 

I stopped on figuring out what we have in progress today, I will be digging into what the API offers and in the worst case, we document that we can't do it for technical limitations.

Does that sounds like a good idea?

**Comment by jcudit** [comment]
> we document that we can't do it for technical limitations

I think this is very good information to surface to the community.  It sounds like you are touching upon a roadmap for this project, which would be a very useful thing to have 😄 .  I'm curious if there are other Terraform providers that do this well or any other project of similar scale.

**Comment by jspiro** [comment]
Could the maintainers enabled Projects so we can track these there? Being one of 120 issues isn't very visible.

Additionally, we're missing organization-wide policies (e.g. permitting public/private pages, SSO, etc.), in the same way that terraform cloud supports terrforming itself.

**Comment by jcudit** [comment]
I've enabled Projects for this repository and can update it with ideas from this thread.  However, I am skeptical about the throughput in which we can burn down these requests.  My hope is that one day we'll get a batch of contributors that will take on these issues.

Given this limitation, organization of upcoming features and fixes has been accomplished with [Milestones](https://github.com/integrations/terraform-provider-github/milestones) and  [Labels](https://github.com/integrations/terraform-provider-github/labels) up to this point.  The most discussed pain points are batched into categories and a milestone focuses on shoring up the specific resource as best possible.

If PRs show up that are out of scope of the current milestone, they take priority and we try to merge them in as contributions do not happen often.  So expect a gradual improvement of long-standing pain points to occur, but the more bleeding-edge or exciting features being up to the heroes of this community to adopt and drive completion.

**Comment by jspiro** [comment]
This would help you achieve more contributors: https://github.com/integrations/terraform-provider-github/issues/677

I've been wanting to contribute for over a year but I can't figure out the local development lifecycle for the life of me.

**Comment by jspiro** [comment]
Incidentally, it looks like only contributors are configured to use Projects. This issue could be merged into Projects, then closed, so we can start to burn down the 123 open issues. Or not... but that was the original idea.

**Comment by jcudit** [comment]
A couple of approaches come to mind:
- Add permissions for your account (or anyone else interested) to manage Projects for this project
- Have contributors "stage" a project board on their fork, to be posted here for discussion / importing into this project

**Comment by psub-github** [comment]
Hello, We are trying to set the Organizational policies where we can set dependency tracking etc. via TF, is there a way to accomplish that? Want to automate the organizational dependency tracking via IAC.

https://docs.github.com/en/enterprise-cloud@latest/admin/policies/enforcing-policies-for-your-enterprise/enforcing-policies-for-dependency-insights-in-your-enterprise.
